apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniapi-staging
  namespace: mini-api
spec:
  secretName: miniapi-staging-certificate
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - miniapi.thinktecture-demos.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniapi-prod
  namespace: mini-api
spec:
  secretName: miniapi-production-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - miniapi.thinktecture-demos.com
